### PR TITLE
Flexible settings policies + WTM_SWITCHER refactor

### PR DESCRIPTION
**Pull request by LuKePicci**
Hope it may be useful to someone, I needed to implement this for my rig since I was trying to optimize oc for using with the autoswitcher but some gpus need lower clocks and I was not so comfortable letting all of them run at those lower clocks.

The switcher script's refactoring il a prep step for doing more refined coin selection in future.

I hope there are not so many bugs. Please test it very carefully with all other switchers also.

### CODE REVIEW

**Comment by leenoox** [comment]
Thanks for your commit. There are some interesting changes but I am against
setting offset to the already applied offset. When we set +100 global core,
that is offset of the original clock. If I understand correctly you are
proposing to set the +100 offset (the way we are doing it now) then offset
the offset again to accommodate different algo.
Why offsetting the offset and not just apply a new per algo offset to the
original clock? This way is kinda confusing, let's say I want -200 core for
ETH and +150 for ZEN. With your proposal I need to set global core to +100
offset, then apply new offset of -300 so I can achieve -200 for ETH or
apply +50 to get +150 for ZEN.
If/When we update for individual per algo OC we should use just one offset
(e.g.. -200 for ETH), no confusions, simple.

Furthermore, for your style, e.g.. [[ $VAR < 30 ]] I don't mind it, it's
nice and clean but if we go with this style then change every single
instance throughout all nvoc scripts to maintain uniformity, not just to
code you commit or adjust to the style already used. It makes it messy when
different styles are used.

Don't get me wrong, these are just my thoughts and ideas. Others might
think differently.
I appreciate your dedication and willingness to improve nvoc. We are small
group of devs and we welcome new additions.

**Comment by LuKePicci** [comment]
Don't worry, I'll be happy to explain.

> Why offsetting the offset and not just apply a new per algo offset to the
original clock? 

When OFFSET policy is selected I'm offsetting the global offset by INDIVIDUAL (per-gpu) values, not by different algo ones. Algo specific values, as I tried to explain in the text in 1bash, but I understand it can be quite confusing, were already implemented as overrides to global ones and I left this behavior unchanged, so if you enable algo-specific oc any algo-specific value replaces the global ones, but than individual values still takes effect on top of the algo-specific in form of offsets (something new that could happen with this patch) or overrides (exactly what happened before my patch).

I agree that a double offset is not so easy to familiarize with, but I think it is a compact way to get both algo-specific and individual clocks different settings combination. Again, with the OVERRIDE policy everything should work as before.

> Furthermore, for your style, e.g.. [[ $VAR < 30 ]] I don't mind it, it's
nice and clean but if we go with this style then change every single
instance throughout all nvoc scripts to maintain uniformity, not just to
code you commit or adjust to the style already used. It makes it messy when
different styles are used.

I absolutely agree. I did not changed all expressions in the codebase since there were too much and I noticed you stick with the old style when I already completed the patch. If I would have modified all other and you won't like the new style it would have been a pita to revert all expressions in the codebase to the old style, moreover I don't like touching every single file in a single commit, especially if the commit is not dedicated to that task. I suggest you to select a style and stick with that convention. I noticed that both [ command and [[ ]] bash semantics were already used in a mixed manner above the entire codebase, that's something you definitely need to address. Since all scripts targets the bash I would argue to select the new [[ ]] semantics, over the old [ command, but I actually don't care.

**Comment by leenoox** [comment]
What I am planning is to make per algo individual card settings for all available algos. Since this would make 1bash extremely long I want to keep only the basic global OC settings in 1bash and move individual card settings for all the different algos in a new file.
This will have simple global settings in 4 lines (core, mem, PL, temp) in 1bash that will apply to all cards and all algos for easy and fast deployment.

Then we would have advanced option to fine tune individual cards and individual algos in new file which would override the global settings from 1bash and will only be applied if the switch is enabled in 1bash (e.g. USE_INDIVIDUAL_SETTINGS="YES").

Again, I wouldn't use offset to the offset to keep it simple and use the way everyone is familiar with.

BTW, I see that you also modified WTM... I can't comment on that, it's papampi's domain.

Papampi, Stubo, damNmad... what are your thoughts on this?

**Comment by LuKePicci** [comment]
I see your point and it will be the only viable option to get per-algo individual settings. What I added here is not in contrast with what you are planning to do, it's just adding the ability to control individual settings application policy. The fact that it allows people in the immediate to benefit from both per-algo and individual fine-tuning capabilities is only a consequence. I also simplified a lot the setup since there are no more POWERLIMIT, INDIVIDUAL_POWERLIMIT, INDIVIDUAL_OVERCLOCK but only a single and consistent policy mode to set.  I think this commit can be a good base for implementing your idea. You could for example have for each algo in the new file you mentioned a section with a setting for all gpus and individual settings that may be interpreted as overrides or offsets against the above values. For example setting in OVERRIDE mode we could have:

```
#####
# ETHASH globals
#####
__CORE_OVERCLOCK=100
MEMORY_OVERCLOCK=1000
POWERLIMIT_WATTS=100
#####
# ETHASH individuals
#####
__CORE_OVERCLOCK_0=100
MEMORY_OVERCLOCK_0=1100
INDIVIDUAL_POWERLIMIT_0=100

__CORE_OVERCLOCK_1=100
MEMORY_OVERCLOCK_1=950
INDIVIDUAL_POWERLIMIT_1=100
```
 etc...

while setting in OFFSET mode we could have

```
#####
# ETHASH globals
#####
__CORE_OVERCLOCK=100
MEMORY_OVERCLOCK=1000
POWERLIMIT_WATTS=100
#####
# ETHASH individuals
#####
__CORE_OVERCLOCK_0=+0
MEMORY_OVERCLOCK_0=+100
INDIVIDUAL_POWERLIMIT_0=+0

__CORE_OVERCLOCK_1=+0
MEMORY_OVERCLOCK_1=-50
INDIVIDUAL_POWERLIMIT_1=+0
```

Doing so it would be pretty quick to setup, you only need to adjust those that need fine-tuning instead of replacing all values each time you would like to try lowering a clock for all gpu.

Again, since it is not a breaking change but an handy addition  and also a good preparation for what you intend to realize I would suggest to merge this.

**Comment by papampi** [comment]
Nice clean up to WTM_SWITCHER
Will put it in my test rig and see how it goes

**Review by papampi — COMMENTED** [review]
Looks good, testing now.

**Comment by papampi** [comment]
I dont ever use mix cards, So I cant say much about it.
But I see many more good additions/fixes/edits in 3main, Thanks.

I'm sure Leenoox can use many of the codes in tempcontrol for our next version
I will make the fixes in 3main code and with your permission will add your name in change logs for wtm and 3main.

**Comment by LuKePicci** [comment]
That's fine.

**Review by papampi — DISMISSED** [review]
"NICE_" should be changed to "NICE-" as there was reports that its not working like that and 1bash variables changed to "NICE-" too

**Review by papampi — COMMENTED** [review]
"NICE_" should be changed to "NICE-" as there was reports that its not working like that and 1bash variables changed to "NICE-" too

**Comment by papampi** [comment]
Cant merge only 1 change from 2, will make changes manually to WTM_SWITCHER

**Comment by papampi** [comment]
Manually made the changes to WTM_SWITCHER.

**Pull request closed without merging**
