### PR TITLE
ALLOWED_FAN_DIFF

### PR DESCRIPTION
**Pull request by papampi**
Give fan speed setting allowed diff limit so it wont change on small differences.

### CODE REVIEW

**Comment by papampi** [comment]
@LuKePicci 
You have any improvements/edits for this?

**Comment by LuKePicci** [comment]
Please add a check on ALLOWED_FAN_DIFF value such that:
- it gets set to 0 if it's not defined
- it gets set to 0 if specified value is negative
- it gets set to (__FAN_ADJUST / 2) if it's set to something greater than __FAN_ADJUST / 2)

Also print a warning for the last two cases.

**Comment by papampi** [comment]
@LuKePicci anything else?

**Review by LuKePicci — APPROVED** [review]
Should be fine now.

**Pull request merged**
