### PR TITLE
Papampi disabled gpus

### PR DESCRIPTION
**Pull request by papampi**
Allowing to disable GPUs and bypass their check

### CODE REVIEW

**Comment by LuKePicci** [comment]
Was @brightskye already working on something similar?

**Comment by papampi** [comment]
No idea, is he?

**Comment by LuKePicci** [comment]
https://github.com/brightskye/nvOC_by_fullzero_Community_Release/commit/6e9fed4ae3f50f1eadfee4c89de4bed32de8dc82

**Comment by papampi** [comment]
@brightskye  
Have a look at my approach
I think when we blacklist and skip the gpu from checking we dont need to count active GPUs anymore, do we?
And your miner implementation is awesome ... 👍 
Here is my watchdog log:

```Wed Jul 18 19:01:36 +0430 2018 - [INFO] - GPU0 Utilization: 100%
Wed Jul 18 19:01:36 +0430 2018 - [INFO] - GPU1 Utilization: 100%
Wed Jul 18 19:01:37 +0430 2018 - [INFO] - GPU2 Utilization: 99%
Wed Jul 18 19:01:38 +0430 2018 - [INFO] - GPU3 Utilization: 100%
Wed Jul 18 19:01:38 +0430 2018 - [INFO] - GPU4 Utilization: 100%
Wed Jul 18 19:01:39 +0430 2018 - [INFO] - GPU5 Utilization: 100%
Wed Jul 18 19:01:39 +0430 2018 - [INFO] - GPU6 Utilization: 100%
Wed Jul 18 19:01:40 +0430 2018 - [INFO] - GPU7 disabled
Wed Jul 18 19:01:40 +0430 2018 - [INFO] - GPU8 Utilization: 99%
Wed Jul 18 19:01:40 +0430 2018 - [INFO] - GPU9 Utilization: 98%
Wed Jul 18 19:01:41 +0430 2018 - [INFO] - GPU10 Utilization: 100%
Wed Jul 18 19:01:41 +0430 2018 - [INFO] - GPU11 Utilization: 100%
Wed Jul 18 19:01:42 +0430 2018 - [INFO] - No mining issues detected, Check again in 15
```


My GPU7 is faulty and excluded in miner as well

Edit:
Actually we need active gpu count or it never get to 100% GPU under threshold.

**Comment by brightskye** [comment]
Hi, 
Glad that you like the implementation, I intent to create a pull request, however, I haven't properly tested my code yet, so it's just sitting in my branch.

Back to your code, I think we still need the active gpu count in watch dog, otherwise it will break some of the logic at the later part.
Another thing i see might have issue is 
line 270 if echo $DISABLED_GPUS | grep -q $GPU 
If anyone has more than 10 gpu, this might break.

I'm still trying to get familiar with github and linux commands, so feel free to incorporate anything u see fit from my code.

**Comment by LuKePicci** [comment]
You're right on the issue with line 270.

I didn't reviewed with attention your branch since you have not created a PR yet but I would encourage you to go on because it feels fine to me. Please, continue discussing with @papampi about the ways of handling the skip in the watchdog.

**Comment by papampi** [comment]
A GPU failed in one of my rigs and I make these changes to keep it running until I can visit it, so let's close this PR and wait for @brightskye to finish it. 
Let me know if you need help or tests or ...

**Pull request closed without merging**
