### PR TITLE
Create sysrq_reboot.sh

### PR DESCRIPTION
**Pull request by papampi**
Do Magic sysrq reboot to prevent system hang/freeze when GPU drops off the bus and lost.

### CODE REVIEW

**Comment by papampi** [comment]
Comment our R.E.I  … typo ... Comment out R.E.I

**Review by LuKePicci — DISMISSED** [review]
Should it be optional or the standard way to perform reboots? Btw if it works I don't see any issue in this PR.

**Comment by papampi** [comment]
Actually I was thinking to add an option in 1bash, so users can choose between normal or syrq_reboot.
Will implement it.

**Comment by Alysko** [comment]
Nice, commit it! ;)

**Pull request merged**
