### PR TITLE
0miner: define unified *_FEE and fix coin *_OPTS variables

### PR DESCRIPTION
**Pull request by LuKePicci**

### CODE REVIEW

**Review by papampi — APPROVED** [review]
Should I fix the conflict or you will do it?

**Comment by papampi** [comment]
COIN_OPTS passing and miner starts fine but eval still gives an error :

```
/home/m1/NVOC/dev/0miner: line 198: --algo: command not found
screen -c /home/m1/NVOC/dev/screenrc-miner -dmSL miner /home/m1/NVOC/dev/miners/Z_EWBF/0.6/miner --fee --server stratum.zel.cash --user MY_ADDRESS.nv100 --pass x --port 2001 --algo 144_5 --pers ZelProof
    

```

**Comment by LuKePicci** [comment]
This is no more a problem with eval, it's just a problem of … too much money: line 198, there is an extra dollar it doesn't like at the beginning. Please fix it directly, It would be quite embarrassing  to open a PR for this...

**Comment by papampi** [comment]
@LuKePicci 
Noticed it adds device list to miner, you did it on purpose?

`screen -c /home/m1/NVOC/dev/screenrc-miner -dmSL miner /home/m1/NVOC/dev/miners/Z_EWBF/0.6/miner --fee --server stratum.zel.cash --user ADDRESS.nv100 --pass x --port 2001 --algo 144_5 --pers ZelProof --cuda_devices 0 1 2
`

**Comment by LuKePicci** [comment]
Not me, it's by selective gpu disable design, if you have not specified a list of enable gpus than it should use all of them, does your test rig contains three gpus? Then its just working.

**Comment by papampi** [comment]
Yup, it has 3 and works fine.

**Comment by papampi** [comment]
Looks like its not passing Z_EWBF_FEE value:

`screen -c /home/m1/NVOC/dev/screenrc-miner -dmSL miner /home/m1/NVOC/dev/miners/Z_EWBF/0.6/miner --fee --server stratum.zel.cash --user ADDRESS.nv100 --pass x --port 2001 --algo 144_5 --pers ZelProof --cuda_devices 0 1 2`

**Comment by LuKePicci** [comment]
Did you update the manifests with ${!xfee} at its place?

**Comment by papampi** [comment]
Was just checking if I edited it or not

**Pull request merged**
