### PR TITLE
Improved gpuinfo display

### PR DESCRIPTION
**Pull request by Alysko**

### CODE REVIEW

**Comment by LuKePicci** [comment]
Please, provide a "before vs after" preview of gpuinfo output as PR description

**Comment by Alysko** [comment]
I just changed the display of gpuinfo() stdout to be in columns.

**Comment by LuKePicci** [comment]
Before
image

After (80 char columns)
image

Compromise proposal (80 char columns)
image

**Comment by Alysko** [comment]
Good idea!

**Comment by LuKePicci** [comment]
Could you do it?

**Comment by papampi** [comment]
Goog idea, But I think it wont be the same with mix card rigs , any idea how to make them with fix indents?
My test rig:
untitled

**Review by papampi — COMMENTED** [review]
Are we getting the "compromise proposal" ?

**Comment by LuKePicci** [comment]
I moved model and vendor at the end to mitigate gpu mix indentation issues, that's why I added a fictitious Gigabyte card at the end. I honestly have not any better idea, maybe asking to community is the way to go.

**Comment by papampi** [comment]
@LuKePicci , Can you please make the changes, so I merge it?

**Comment by papampi** [comment]
@LuKePicci please dont forget to add dev revision, I noticed you forgot to do it in last PR.

**Review by papampi — COMMENTED** [review]
@Alysko Thanks mate, I can merge it now if you dont want to add your name to dev revisions.

**Comment by Alysko** [comment]
I've just made a modification to be more compact. I suppressed decimals to power display: I dont' think it's useful.

**Review by papampi — APPROVED** [review]
Thanks mate.

**Comment by LuKePicci** [comment]
I’m sorry but I wasn’t sure if my PR would have been the next revision. I think the best thing is that you do the increment directly into the merge commit. This should be better also for other occasional contributors.

Da: Payam Nab
Inviato: lunedì 23 aprile 2018 13:46
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] Improved gpuinfodisplay (#42)

@LuKePicci please dont forget to add dev revision, I noticed you forgot to do it in last PR.

**Pull request merged**
