### PR TITLE
Implemented programatic switch having the 2.1 as base branch

### PR DESCRIPTION
**Pull request by goldmang**
Based on @salfter’s switchers i’ve implemented a programatic switcher, where the input would be a over-the-internet-accessible-json-file (could be hosted in google drive, pastebin, etc) having the following format:

```
{
  "RIG_HOSTNAME1": {
      "current_miner": {
          "algo":"Cryptonight",
          "coin_currency":"COIN_SYMBOL",
	      "host":"POOL_HOSTNAME",
          "port":POOL_PORT,
          "user_name":"CRYPTONIGHT_BASED_COIN_WALLET_ADDRESS"
      }
  },
  "RIG_HOSTNAME2": {
      "current_miner": {
          "algo":"Cryptonight-Heavy",
          "coin_currency":"COIN_SYMBOL",
	      "host":"POOL_HOSTNAME",
          "port":POOL_PORT,
          "user_name":"CRYPTONIGHT_BASED_COIN_WALLET_ADDRESS"
      }
  }

}
```

It is usefull when you have multiple rigs and want to quickly switch to a new algo for spec minig purposes.
I’ve also added the beta [xmrig-nvidia](https://github.com/xmrig/xmrig-nvidia/tree/feature-cryptonight-heavy) in `/home/m1/xmr/xmrig-nvidia/` folder for the `Cryptonight-Heavy` algo (haven, sumokoin) in the config file.

### CODE REVIEW

**Review by LuKePicci — COMMENTED** [review]
For me is more then good, at least after a second quick look. I have only two things to point out.
1) You should not push a 1bash with coin changed to SALFTER_PROGRAMATIC_SWITCHING because the settings you see in 1bash in this repo should be considered the default one for the branch it belongs to (at least I think so). Then users will have to choose SALFTER_PROGRAMATIC_SWITCHING to enable the programatic switch as you did.
2) Take a look at my OC policy PR #37  and, without taking any action modifying your code please tell me is there could be some problems adapting your version to the modified salfter switch you find there

**Comment by LuKePicci** [comment]
Seems fine to me now, just see what @leenoox says about this.

**Comment by LuKePicci** [comment]
@goldmang add a mention to this new switcher in 1bash after line 209

**Comment by goldmang** [comment]
I’ve added a short description besides the switcher name.

**Review by LuKePicci — APPROVED** [review]
If you tested it and it's working fine for me this can be merged.

**Comment by papampi** [comment]
Since leenoox is MIA, lets merge it ...

**Pull request merged**
