### PR TITLE
Versioning 

### PR DESCRIPTION
**Pull request by papampi**
Unified nvOC version reporting

### CODE REVIEW

**Comment by LuKePicci** [comment]
Please, add version reporting to nvOC report for files not previously versioned. Also check that the report works fine with the new versioning scheme.

**Comment by papampi** [comment]
Why its not showing the conflicts from #146  latest commit?

**Comment by LuKePicci** [comment]
because it is not conflicting

**Comment by papampi** [comment]
So it wont undo last changes to 3main or nvOC from #146?

**Comment by LuKePicci** [comment]
Nope, it will only apply those changes you see in this PR diff, otherwise the whole git version control would have been a "suicide philosophy"

**Comment by LuKePicci** [comment]
Is this ready for being merged?

**Comment by papampi** [comment]
Almost done should do some more tests tomorrow, too tired today.

**Comment by papampi** [comment]
I think its done:
```
Operating System info:
Kernel        :  4.4.0-131-generic
OS            :  Ubuntu 16.04.4 LTS
System        :  (gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
nvidia driver :  384.130

nvOC info:
nvOC path     :  /home/payam/nvoc/testing
nvOC          :  0019-2.1 
Report        :  0012
1bash         :  0032
3main         :  0024
5watchdog     :  0020
6tempcontrol  :  0006
wtm switch    :  0022
wtm profit    :  0004
pool switch   :  0002
minerinfo     :  0008
```

Anything left to add?

**Comment by papampi** [comment]
```nvOC info:
nvOC path     :  /home/payam/nvoc/testing
nvOC          :  0019-2.1 
Report        :  0012
1bash         :  0032
1bash.template:  0032
3main         :  0024
5watchdog     :  0020
6tempcontrol  :  0006
wtm switch    :  0022
wtm profit    :  0004
pool switch   :  0002
minerinfo     :  0008
```

**Comment by papampi** [comment]
Ready to merge ...

**Review by LuKePicci — APPROVED** [review]

**Pull request merged**
