### PR TITLE
add CRYPTONIGHTHEAVY

### PR DESCRIPTION
**Pull request by moi162001**
but command line not ok i work on
SCREEN -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/xmr-stak/xmr-stak_miner -a cryptonight-heavy

### CODE REVIEW

**Comment by papampi** [comment]
Are you sure?
Its just a simple a or b condition.

**Comment by papampi** [comment]
Got it
Please try this:

```
  if [[ $ALGO == "CRYPTONIGHTV7" ]] ; then ;   UCCALGO="--currency monero7" ; fi
  if [[ $ALGO == "CRYPTONIGHTHEAVY" ]] ; then ;   UCCALGO="-a cryptonight-heavy" ; fi
  HCD=${NVOC}/miners/xmr-stak/xmr-stak_miner
  eval $LAUNCH $HCD  $UCCALGO --noCPU --noAMD -o "${!xpool}":"${!xport}" -u "${!xaddr}""${!xwallet}""${!xwork}" -p "$MINER_PWD" -i 0

```

**Comment by moi162001** [comment]
good idea variable for algo  but i find algo with a coin !
i check if possible to chnage CRYPTONIGHTHEAVY to cryptonight-heavy for the -a variable an this is a same problem for etash 
(( ps ) sorry for my english ))

**Comment by papampi** [comment]
Same problem for ethash?
I have no problem mining ethash coins and none other reported that.
We cant use cryptonight-heavy in our variables as "-" breaks some bash scripts, it should be cryptonight_heavy, cryptonightheavy, cnheavy, ...

**Comment by papampi** [comment]
Also I didnt understand what you meant by "i find algo with a coin !"

**Pull request closed without merging**
