### PR TITLE
[WIP] Implemented a programatic switcher based on salfter mph and nicehash work

### PR DESCRIPTION
**Pull request by goldmang**
Based on @salfter’s switchers i’ve implemented a programatic switcher, where the input would be a over-the-internet-accessible-json-file (could be hosted in google drive, pastebin, etc) having the following format:

```
{
  "RIG_HOSTNAME1": {
      "current_miner": {
          "algo":"Cryptonight",
          "coin_currency":"COIN_SYMBOL",
	      "host":"POOL_HOSTNAME",
          "port":POOL_PORT,
          "user_name":"CRYPTONIGHT_BASED_COIN_WALLET_ADDRESS"
      }
  },
  "RIG_HOSTNAME2": {
      "current_miner": {
          "algo":"Cryptonight",
          "coin_currency":"COIN_SYMBOL",
	      "host":"POOL_HOSTNAME",
          "port":POOL_PORT,
          "user_name":"CRYPTONIGHT_BASED_COIN_WALLET_ADDRESS"
      }
  }

}
```

It is usefull when you have multiple rigs and want to quickly switch to a new algo for spec minig purposes.

**Todo**

- [x] Add variable for the remote json config file in `1bash` as it is hardcoded in `programatic_switcher`

### CODE REVIEW

**Comment by papampi** [comment]
Nice idea...
Posted in discord beta testing for more testing

**Comment by LuKePicci** [comment]
I like it too, but this should be merged into a dedicated feature branch derived from 2.1

**Comment by goldmang** [comment]
i’ve also added the beta [xmrig-nvidia](https://github.com/xmrig/xmrig-nvidia/tree/feature-cryptonight-heavy) in `/home/m1/xmr/xmrig-nvidia/` folder for the `Cryptonight-Heavy` algo (haven, sumokoin) in the config file:
```
{
  "RIG_HOSTNAME": {
      "current_miner": {
          "algo":"Cryptonight-Heavy",
          "coin_currency":"XHV",
	      "host":"POOL_HOSTNAME",
          "port":POOL_PORT,
          "user_name":"CRYPTONIGHT_BASED_COIN_WALLET_ADDRESS"
      }
  }
}
```

**Comment by goldmang** [comment]
I’ve created another PR (https://github.com/papampi/nvOC_by_fullzero_Community_Release/pull/38) that is based on the 2.1 branch. Not sure what to do with this one? Shall i abandon it?

**Pull request closed without merging**
