### PR TITLE
web info optimizations

### PR DESCRIPTION
**Pull request by papampi**
Instead of filtering miner log and only show good info, show all and add new section to highlight  errors and rejects
Add a new "clear alerts" on top

### CODE REVIEW

**Comment by papampi** [comment]
@LuKePicci This statement not working,
WTM URL Hash Rate: .... should show up when AUTO_SWTCH == WTM_SWITCHING, but it wont https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/7a8f2d4dc531c54a02c5f84fb887adea9cb363a0/www/cgi-bin/minerinfo#L339-L341

Cant fix it, you have any idea?

**Comment by papampi** [comment]
@LuKePicci webinfo not reading exported ALGO from 3main ...

**Comment by papampi** [comment]
@LuKePicci 
I think we talk about algo settings in 3main once before but I forgot why you said they cant be in 1bash and better to be in 3main

**Comment by LuKePicci** [comment]
Maintainability and streamlined upgrading experience. The only other option is to move it in a separate script.

For example you can just set both algo and miner in a single script, and let 0miner launch the correct miner. Such decoupling will let us add a new coin which use an already added miner by just adding it in such separate script. 1bash must be kept untouched between minor updates such that a bit pull is very unlikely to rise conficlts. You can also call thy same script from.minerinfo without launching any miner, you would also get some useful info about which miner should be running at the moment.

**Comment by LuKePicci** [comment]
You are using bad syntax on many if statements, you have to choose if using [[ bash extensions or the old test ( '[' ) command. Only the first one allow you to do efficient string comparison without the need of always quoting string constants and variables (in case they're not set).

**Comment by papampi** [comment]
It's impossible to keep 1bash untouched for upgrades (minor or major) there are so many variables from Temp, Power, OC, PL, fan speed, wallets, ... 
The only way is to add separators/identifiers for each section and replace those section with some simple sed command in upgrade script and notify user to check/edit those sections.
Separating 1bash into multiple files will confuse users so instead of editing 1 file they have to edit multiple files and again on upgrades they have to edit some ...
We have talked about the separate wallet file many times and it's the same. 

As I said before I think we should move "ALGO identification" to 1bash to simplify editing and adding coins and easier read by all other scripts and users dont need to edit 3main incase they wanted to add new coins. 

I already tried double bracket, that is not the problem.

**Comment by LuKePicci** [comment]
The double bracket should solve your issue with wtm_switching if block not being entered.

Never though to split 1bash user settings, but only to move algo identification code outside of 3main.

There was a misleading on what I intend with keeping 1bash untouched, but don’t care. 

If you really need to know which is the algo move that chunk of code out, which is not user settings, outside of 3main in a new file. Will come in handy in other cases also.

**Comment by papampi** [comment]
Already tried double bracket on wtm_switcher statements too ... no idea why its not working

**Comment by LuKePicci** [comment]
@papampi just merge my hotfix branch into this one to get this PR fixed. I cannot push to this branch.

**Comment by papampi** [comment]
It still can't get ALGO from 3main
webinfo shows:
`WTM URL Hash Rate: Not Available 
`

**Comment by LuKePicci** [comment]
Of course, the web server neither shares the environment of 3main nor it's a subprocess. Will address that inconvenient in a future PR. This one is fine, If you do not intend to do more changes you can merge.

**Review by LuKePicci — APPROVED** [review]

**Pull request merged**
