### PR TITLE
Flexible OC settings policies

### PR DESCRIPTION
**Pull request by LuKePicci**
That is a subset of what I committed some time ago regarding support for OC policies whit lot of refactored code. As @leenoox pointed out the OFFSET policy may raise relevant confusion to users, so I removed all references to that policy from 1bash.

Removing/commenting out the actual implementation of the OFFSET policy it's trivial as well but will honestly make me crazy each time I need to push something to remember enabling disabling code blocks (since I need it a.t.m. 😅 )

### CODE REVIEW

**Comment by LuKePicci** [comment]
I also updated the description of algo-specific oc setting in a way it's more clear and ready for algo-specific individuals, as soon as they will be implemented.

**Comment by papampi** [comment]
Looks good to me

**Comment by papampi** [comment]
@leenoox 
If you dont have any comments we can go ahead and merge this ...

**Comment by LuKePicci** [comment]
Will test the main elements asap, but needs to be also checked by someone using or already having a valid satup for at least one kind of salfter-based switcher to be sure it's not broken.

**Comment by LuKePicci** [comment]
Just checked out this branch on a new folder on my rig, the complete switchover between branches taken less time then an usual crash recovery 💪.

Will run some time in single mining then I'll test again with WTM switching.

**Comment by papampi** [comment]
@LuKePicci If your tests are done we can go ahead with merge

**Comment by LuKePicci** [comment]
I'm currently in the middle of an hardware  post-upgrade monitoring phase of my rig and I'm yet to test WTM. If you want to test it now checkout this branche and test, otherwise I ask you to wait a bit.

**Review by papampi — COMMENTED** [review]
Why removed only miner restart when same algo or no algo specific oc?
On 12+ card rigs restarting 3main will make miner restart takes more than 2-3 minutes, while only restarting miner will take only 10-20 seconds.
When OC not changed, we dont need 3main restart.

**Comment by LuKePicci** [comment]
I'm aware of the 3main long start time.
I'm now identifying which is the main time consuming task performed by 3main before miner is started.
Please note that differently from 2.0 tree, in this branch there are lot of optimizations in that sense. For example, nvidia-smi is not called anymore 18 times regardless of the number of installed gpu, PL are set before killing the miner, so this downtime interval is non-existing. Finally I'm about to dramatically decrease the total time needed to call all nvidia-settings. If you know which other task in particular will take in 3main so much time to restart the 3main let me know, then if we still have the problem of huge time interval needed for 3main restart I'll try to address this.

**Comment by LuKePicci** [comment]
I completed testing the WTM_SWITCHER, now is fine. I think I also fixed an issue in case AUTO_STAR_MINER was set to NO.

Regarding the 3main restart time, take a look at those two simple cases:


- time (nvidia-settings -a [gpu:8]/GPUFanControlState=1 -a [fan:8]/GPUTargetFanSpeed=40)


  Attribute 'GPUFanControlState' (m1-desktop:0[gpu:8]) assigned value 1.

  Attribute 'GPUTargetFanSpeed' (m1-desktop:0[fan:8]) assigned value 40.


real    0m0.514s
user    0m0.052s
sys     0m0.216s


- time (nvidia-settings -a [gpu:8]/GPUFanControlState=1; nvidia-settings -a [fan:8]/GPUTargetFanSpeed=40)


  Attribute 'GPUFanControlState' (m1-desktop:0[gpu:8]) assigned value 1.


  Attribute 'GPUTargetFanSpeed' (m1-desktop:0[fan:8]) assigned value 40.


real    0m1.127s
user    0m0.144s
sys     0m0.448s

If you consider it was calling that command once for each gpu clock, mem clock, fancontrol and fanspeed this roughly means it now takes up to 4*GPU# times less then before.

If you have any chance of testing against a 12+ gpu rig let me know how much it takes in practice.

**Comment by papampi** [comment]
Last commit seems like a great time saving, unfortunately my test rig has only 3 cards and main rigs are remote and cant test on them.
Lets go forward and see how it goes ...

Usually what I noticed was that setting OC, PL and fan take the most times and then tempcontrol start takes long time if p106 headless is no in this case all processes waits till tempcontrol finishes loading then starts, but when p106 set to yes, wtm, watchdog and miner start while tempcontrol is still loading and setting fan speed and ...

**Comment by LuKePicci** [comment]
I can only say that on my 9 gpu rig it now takes much less than before, and the miner itself is down for a very little time if 3main does not need to restart nothing else (I mean if it finds that watchdog tempcontrol and wtm is already up

**Comment by LuKePicci** [comment]
I'll now do some rework on HEADLESS/TI OC management, (was completely missing, I don't know why) but please review carefully because I can't test it.

**Comment by papampi** [comment]
WTM should stop watchdog before restart 3main or it will catch low utilization and restart 3main again and will send telegram alert if its enabled. 
Also 3main has a re-up tempcontrol, to restart it if its running (no idea why) 

Now that we are on 3main edits 
What do you think about changing all the instances of 
```
running=$(ps -ef | awk '$NF~"PROCESS" {print $2}')
if [ "$running" == "" ]; then...
```

to 

```
if ! ps ax | grep -q '[P]ROCESS'; 
then 
  start PROCESS
```

**Comment by papampi** [comment]
I can test p106 headless, dont have any TI cards, also noticed some users has issue on p104 OC in discord and @Doftorul posted this:

> Option         "AllowEmptyInitialConfiguration" "True"
>     Option         "ConnectedMonitor" "DFP-0"
> this needs to be added to xorg.conf in order to allow for the P104 to overclock

Shall we change the p10x xconfig 
from:
`      sudo nvidia-xconfig --enable-all-gpus --cool-bits=12
`
to:
`nvidia-xconfig -a --enable-all-gpus --allow-empty-initial-configuration --cool-bits=28 --use-display-device="DFP-0" --connected-monitor="DFP-0"
`

**Comment by LuKePicci** [comment]
Wait.
1) there is something strange with clocks settings if full_headless is yes, don't know why but seems that 3main was only applying global clocks even if INDIVIDUAL was YES, was this intentional?
2) it still kills watchdog before killing 3main, as it was before
3) ok for changing nvidia-xconfig command line I have no idea what it does but I will try to make this work at least as well as it works now.
4) if that `if ! ps ax |`is the same why not

**Comment by LuKePicci** [comment]
I think those further modification should be part of another PR: this one could be merged as is now.

**Comment by papampi** [comment]
1. No idea where is that bug, dont think its intentional.
2. Was just saying watchdog should get re-up, and dont know if its needed to re-up tempcontrol too?
3. I have no idea too, just posted @doftorul post from discord.
4. will make changes after you done magic ;)

**Review by papampi — APPROVED** [review]
If you think this PR is ok, lets merge it then ...

**Comment by LuKePicci** [comment]
1) all OC/PL apply commands are called inside an if full_headless == NO block, otherwise only global clocks are applied, which in the old OC management would have basically broken INDIVIDUAL clocks only, while ALGO_SPECIFIC were hidden from 3main perspective, so it was "accidentally working".
2) yeah, 6tempcontrol always get  killed and relaunched while watchdog is only launched if is not running, I think is good as it is for now, there is no reason to stop and re-up watchdog at every 3main restart if this is not cause by auto switcher, and tempcontrol needs re-up to get updated OC settings in case of algo-specific settings.
3) My changes to headless-related code will likely break things since I'm totally blind on that topic.

**Comment by papampi** [comment]
You mean this part:
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/2874bde7edc94247fd3dc5a3f15c37f9f003ec3c/3main#L1057-L1091

It seems like the last loop is outside if p10x == no and should go inside

Then we have this for p10x headless, doesn't this apply oc to all cards?
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/2874bde7edc94247fd3dc5a3f15c37f9f003ec3c/3main#L1117

**Comment by LuKePicci** [comment]
That last line (1117) from my point of view should be simply removed, and the content of the if block should all be outside, otherwise manual fan settings are not taken into account in full_headless mode,

But I don't know the reason for being such previously.

Then the xorg update should be performed somewhere else but have some concerns about the requirements for headless mode in terms of xorg.conf contents.

**Pull request merged**
