### PR TITLE
watchdog lost gpu check

### PR DESCRIPTION
**Pull request by papampi**
In case of lost GPU watchdog restart miner first and if it didnt work reboots

### CODE REVIEW

**Comment by papampi** [comment]
Do we need to read all the card info here in watchdog?
I think only utilization is enough.

    { IFS=', ' read UTIL CURRENT_TEMP CURRENT_FAN PWRLIMIT POWERDRAW ; } < <(nvidia-smi -i $GPU --query-gpu=utilization.gpu,temperature.gpu,fan.speed,power.limit,power.draw --format=csv,noheader,nounits)


Edit:
Sure we need them for non numeric check ...

**Comment by papampi** [comment]
But in case GPU lost we get non numeric on util too, so we dont need 1050 test either if we only check utilization?

@leenoox Am I missing some thing?

**Comment by papampi** [comment]
@LuKePicci 
What do you think?

**Comment by LuKePicci** [comment]
I think you should be right

________________________________
Da: Payam Nab <notifications@github.com>
Inviato: Saturday, March 9, 2019 1:46:37 PM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] watchdog lost gpu check (#270)


@LuKePicci<https://github.com/LuKePicci>
What do you think?

**Comment by papampi** [comment]
Yup, 
Tested only with UTIL and my latest watchdog commit
Removed a usb riser 
UTIL gave numeric error
3main got restarted, then rig restarted as it couldnt solve the issue.

**Comment by papampi** [comment]
I believe that's all...
@LuKePicci if you don't have any thing to add/edit, we can merge it.

**Review by LuKePicci — APPROVED** [review]

**Pull request merged**
