### PR TITLE
WTM python check changes

### PR DESCRIPTION
**Pull request by papampi**
Remove WTM python check from watchdog and add it to wtm_auto_switch and wtm_profit_check

### CODE REVIEW

**Comment by papampi** [comment]
Tested and working fine.

**Review by LuKePicci — APPROVED** [review]
Makes sense.

**Comment by papampi** [comment]
@LuKePicci any idea why 
This shows grep too?
```
m1@m1-desktop-112:~$ ps ax | grep  [W]TM_SWITCHER
17142 pts/19   S+     0:00 grep --color=auto WTM_SWITCHER ```

**Comment by LuKePicci** [comment]
Sure, grep is a process that reads from stdin (the pipe), so it runs before `ps ax`, therefore it lists also grep as a process and it also matches the grep expression since it contains [W]TM_SWITCHING in the command line as well. To avoid this you can either use pgrep which seems to handle this automatically, or you can put "... | grep -V grep | …" in the middle.

**Comment by papampi** [comment]
But why this one does not include it:

`m1@m1-desktop-112:~$ ps ax | grep  [WTM]_SWITCHER`

**Comment by papampi** [comment]
I was thinking the point to use brackets is to remove the grep from showing itself

**Comment by LuKePicci** [comment]
Maybe it has something to do with the injection of --color=auto argument.

**Pull request merged**
