### PR TITLE
Pluggable miners

### PR DESCRIPTION
**Pull request by LuKePicci**
This should allow additional miners to be plugged into nvOC even easier without the need of editing a single line of code within nvOC scripts.
Supports a pluggable miner definition json file like those included in nvOC_miners packages
For now, only ethminer 0.14.0 has been converted to a pluggable miner.
The implementation is completely general for any algo and does not break the current implementation. This is pretty fine during development and until all miners packages will be converted.
- if miners/${!${ALGO}_MINER}/${${!${ALGO}_MINER}}_VERSION/nvoc-miner.json exists it is parsed
- else if miners/${!${ALGO}_MINER}/nvoc-miner.json it is parsed

Note:
- ${${ALGO}_MINER} must match the folder name to allow pluggable miner definition to be found
- Since ethminer is inside "ethminer" folder setting ETHASH_MINER="ETHMINER" won't catch any of previous cases because of case-sensitiveness of paths, then the old implementation take place.

### CODE REVIEW

**Comment by papampi** [comment]
I don't quite understand this.
So every coin needs a miner with this plugable miner?

**Comment by LuKePicci** [comment]
Nope, because after @sizzlephizzle unification each miner launch definition is unique for any coin. if *_MINER="something_that_is_a_pluggable_miner" parse miner-specific info from the json manifest. Practically, nothing changes for existing miners, new miners can be added without editing 0miner or minerinfo. In other words no more hard-coding of miner-specific stuff is needed, the algo->miner binding is no more hard-defined. I converted just ethminer 0.14.0 to have something to test with, but we don't strictly need to convert the others. Additionally, converted miners are still backward compatible with old code.

For example, if a new miner for Zhash or any other _already supported algo_  we don't need anymore to wait for patches to any nvOC script, you just need to plug the new miner in., every needed miner-specific detail is in the manifest.

This is great for various future evolutions. Think about what you now need to do to support a new algo.  How many lines do you need to patch _exactly_ outside of 1bash?

@doftorul was thinking to something that allows large-scale provisioning of miners and will probably love this.  For example, in the miner manifest, you can change the script that grab the hashrate info and query the miner api if exists. You can start mining with a new coin/algo/miner by just editing 1bash and plugging in a miner, you can wait for the plugguble mienr to be part of nvOC_miners or you can make it by yourself and plug it in immediately on every single nvOC instance, and it will work the very same way. All those things are easy to be managed by a web dashboard if somebody will ever try to make one. You will just need a webform with modelbinding to the manifest.

This is still WIP, I'm now evaluating the necessity of having different command line templates for each algo supported by a miner if it supports more than one. I would also like to address the case of xmr-stak which require some commands to be executed before launching. Meanwhile take a look at the converted 0.14.0 ethminer package in my nvOC_miners feature branch.

**Comment by LuKePicci** [comment]
I was evaluating if it would the case to postpone this to the next 3.1 dev branch, but I think if we pull this into 2.1, once released, we will be able to update miners without patching the 3.0 codebase, should be easier to support 3.0 for long time in case new algos spawn. What do you think?

**Comment by papampi** [comment]
I think the idea is great, but if we gonna make it ready for 3.0, we should add it to all current miners and not just some and it gonna take time to test each and every coin/miner.
Also I think its better that the miner.json file not be inside the tar file so it would become easier to edit and doesnt need to patch it to every miner update

**Comment by LuKePicci** [comment]
If it will be included in 3.0 then no existing miner should be shipped as pluggable, we just have support for the new type, in case new ones has to be added. I have no intention to convert existing ones in 2.1, I just did it for ethminer for testing, I will revert back the nvOC_miners submodule dependency to the default 19-2.1 branch such that also ethminer is shipped the "old" way. So no further testing is required.

Regarding the manifest file, I had this feeling also, It is very disturbing to repack the tarball every time for each modification, but to sort this out we need some more complex miner installation. You know, the manifest is related to a specific binary version, if I simply put it outside the tarball it gets updated by git before the actual binary extraction, and remains updated even if users choose not to update miners, and this breaks things. We need to do some compromises between simplicity in miner addition workflow and straightforward editing of such a manifest. How frequently this manifest needs to be edited _after_ being released. While creating you can leave there as it is installed so you don't have to repack each time, you only need to pack when pushing in the repo.

**Comment by papampi** [comment]
Cant test, have the same tempconrol problem as https://github.com/papampi/nvOC_by_fullzero_Community_Release/pull/165

**Comment by papampi** [comment]
I see so many edits, commits and changes. 
Are you sure you want to push this to 19-2.1 and main release?
I'm sorry, but I really dont have time to test and check all the changes now.

**Comment by LuKePicci** [comment]
You see many edits because it is set to 3.1 as base branch. The pluggable miner mechanism is working fine for ethminer even in minerinfo, I have it running for some days with crazy switching between dstm, z_ewbf and pluggable ethminer with no issues. I see people asking how to define new algos in the forum so it would be great to have it released asap, 3.1 will probably focus on multi instances so it will require very long time to work on. I managed to get pluggable miners to coexist with old builtin ones to have this working at least like it was before this PR, The only thing I think it is worth testing is cpumining,
Most relevant changes are in:
- 0miner, some more unified variables and two if branches
- minerinfo: same thing
- 1bash.template: some more comments and movements
- 3main the cpumining part
- 0cpuminer: which resambles 0miner

All you see edited in watchdog, temp control, wtm and the 3main part relative to salfters are merged already in 2.1, you can change the base branche and you should not see anymore in changes.

**Review by papampi — APPROVED** [review]
Fingers crossed 👍

**Pull request merged**
