### PR TITLE
Rework 6tempcontrol activity in abnormal situations

### PR DESCRIPTION
**Pull request by LuKePicci**
Different approach in handling unresponsive gpus. I need to test this further. Let me know if you catch something bad at a first glance.

- Unified handling of gpus which do not support reading of `power.draw` value (ie  GeForce 1050)
- Keep looping for temp updates even if some gpu is not responding - gpu polling continues in background

Needs some work to prevent a doubling the unresponsive gpu polling (and warnings) if it is still unresponsive at the next iteration, but should work anyway also like this.

### CODE REVIEW

**Review by papampi — APPROVED** [review]
Looks good

**Comment by papampi** [comment]
@LuKePicci 
A while back @delawr0190 had a great idea on how we handle nvidia-smi calls,
We can have a nvidia-smi-helper which reads nvidia-smi values in given intervals and send them to a file, then watchdog, tempcontrol and foreman can read from it instead of running separately.
It will reduce nvidia-smi calls significantly and we can handle errors much better.

**Comment by LuKePicci** [comment]
It's almost like this already, we just need to write the contents of the smi_query output variable into a file so other jobs can read from there. Before this patchset, in case of errors the regular smi querying was delayed, so other processes would have been unable to get a fresh query output. Now you can, since it's done regularly and independently in the background.

However, moving the smi querying outside of tempcontrol is a good thing in concept, but I have no good ideas on how to implement ivia bash scripting a nice publisher (smi helper) & subscriber (tempcontrol) for this, and falling back to simply regular polling by tempcontrol on shared smi outputs is not very nice since it will create delays between value readings and fan adjustments. Let's assume the smi-query helper will not perform more queries then what tempcontrol currently does (it is the most frequent consumer of smi output data) and tempcontrol is set in such a way that its main loop period equals to 30 seconds. If we run smi helper and tempcontrol asynchronously (ie tempcontrol activity not triggered immediately when new smi values are available), we could end up with tempcontrol taking actions based on values up to 30 seconds old since nvidia-smi always takes a different amount of time to complete executions, so at a certain point you will for sure get into this "bad" situation that would require a much more complex control routine to achive temp stability. A naive solution is to increase smi query frequency, but this would go in the opposite direction with respect to smi queries reduction.

On the other hand, tempcontrol is currently something that can be disabled in 1bash, so if we go for smi output sharing we will either need to run it in any case or adapt other programs to go for their own smi queries if tempcontrol is disabled.

I will update this to regularly flush smi output to a file, see with @delawr0190 if it is enough for him to just read from there or it would require something more.

**Comment by papampi** [comment]
I get you, but check this:
tempcontrol default sync time is 15 sec, 4 times every minute.
watchdog default sync is 15, 4 times every minute.
Foreman once every minute.

So we run nvidia-smi 9 times every minute, every 6-7 seconds, we can set it to run every 10 seconds and all the scripts get almost fresh data on every cycle.
Dont you think it will be much better?

We can set it to run if either of the 3 scripts are set to yes, or set the sync time intervals by how many of the 3 are enabled. 
So if all set to yes, it syncs every 10, if only watchdog or tempcontrol is enabled, then run every 15 and if only foreman enabled run every 1 minute or some thing like that.

**Comment by papampi** [comment]
We can also set the helper to be called from the scripts that needs nvidia-smi query instead of 3main and check timestamp, so for example if data was older than 10 sec run it and if its already running and querying data sleep a bit and then get the fresh data.

**Comment by delawr0190** [comment]
@papampi

I’d be more than happy to work on this if needed.

For Foreman, we need the following information:

Name
Bus ID
Core clock
Memory clock
Fan
Temp

**Comment by papampi** [comment]
@delawr0190 
Thanks mate,
I'm not much of an expert in json read/write, maybe @LuKePicci can use your helps if we get to an agreement on this.
 
For Foreman, I think we can run the helper once from 3main before applying memory and clock OC to have default values then after each cycle it can subtract the values to give us the added OC, so users can be sure their OC values are applied.

**Comment by LuKePicci** [comment]
>           We can also set the helper to be called from the scripts that needs nvidia-smi query instead of 3main and check timestamp, so for example if data was older than 10 sec run it and if its already running and querying data sleep a bit and then get the fresh data.

I like this. It's both simple and optimal.

**Pull request merged**
