### PR TITLE
Check rig load avearge

### PR DESCRIPTION
**Pull request by papampi**
If 1, 5 and 15 min load average are more than double CPU core give warning.

Just an idea, what you guys think?

### CODE REVIEW

**Comment by LuKePicci** [comment]
Mayne @doftorul could benefit from such a reporting feature.

**Comment by papampi** [comment]
It's just an alert, we can add a reboot option for it in 1bash too.

**Comment by papampi** [comment]
If nothing against this, we can merge it.

**Review by LuKePicci — DISMISSED** [review]
For me is fine, go merge this one also.

**Pull request merged**
