### PR TITLE
Dual cuda, define old miners

### PR DESCRIPTION
**Pull request by papampi**
Define list of old miners that only support cuda 8 and use cuda-8 ENV
I think we should remove algo_cuda and use the list of miners instead

### CODE REVIEW

**Comment by LuKePicci** [comment]
Such information about default target cuda runtime should be inside the pluggable miner manifest, makes no sense maintaining a user-defined list of miner names, the user has already control on the target runtime override in 1bash, so I think we have all we need already, given that cuda runtimes are also backward compatible.

**Comment by papampi** [comment]
Didnt know they are backward compatible. 
Will test and edit this.

**Comment by LuKePicci** [comment]
Sure, for example I have cuda 9.1 as default in path, no custom cuda runtimes selected in 1bash and every miner runs just fine when compiled against their correct sdk version.

**Comment by papampi** [comment]
Awesome, then we can close this PR and just make the changes in https://github.com/papampi/nvOC_miners/pull/19/

**Comment by LuKePicci** [comment]
I'm about 500 miles away from my rig at the moment so I can't play with cuda stuff on it, I will spend some time in reading documentation and see what can I do.

**Comment by papampi** [comment]
Tried ASccminer and SPccminer, both gave error on cuda-9 and quit
```
/home/m1/NVOC/mining/miners/ASccminer/ccminer: error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory
/home/m1/NVOC/mining/miners/SPccminer/ccminer: error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory
```

**Comment by papampi** [comment]
Tried to run with cuda-8.0 path and it gave permission error, and had to run with root permission.

**Comment by papampi** [comment]
Screen not start when try to run with path:
```
m1@m1-desktop:~$ PATH=/usr/local/cuda-8.0/bin:/home/m1/bin:/home/m1/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64: screen -c /home/m1/NVOC/mining/screenrc-miner -dmSL miner /home/m1/NVOC/mining/miners/ASccminer/ccminer -a neoscrypt -o stratum+tcp://stratum.aikapool.com:7905 -u papampi.nv100 -p x -i 14
m1@m1-desktop:~$ screen -r miner
There is no screen to be resumed matching miner.
```

But it runs without screen:


```
m1@m1-desktop:~$ PATH=/usr/local/cuda-8.0/bin:/home/m1/bin:/home/m1/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:  /home/m1/NVOC/mining/miners/ASccminer/ccminer -a neoscrypt -o stratum+tcp://stratum.aikapool.com:7905 -u papampi.nv100 -p x -i 14
*** ccminer alexis-1.0 for nVidia GPUs from alexis78@github ***
*** Built with the nVidia CUDA Toolkit 8.0 (Not recommended prefer 7.5)

*** Based on tpruvot@github ccminer
*** Originally based on Christian Buchner and Christian H. project
*** Include some of the work of djm34, sp, tsiv and klausT.

[2018-08-05 09:17:11] Starting on stratum+tcp://stratum.aikapool.com:7905
[2018-08-05 09:17:11] NVML GPU monitoring enabled.
[2018-08-05 09:17:11] 3 miner threads started, using 'neoscrypt' algorithm.
[2018-08-05 09:17:14] Stratum difficulty set to 128 (0.00195)
[2018-08-05 09:17:14] GPU#0:Intensity set to 14, 16384 cuda threads
[2018-08-05 09:17:14] GPU#1:Intensity set to 14, 16384 cuda threads
[2018-08-05 09:17:14] GPU#2:Intensity set to 14, 16384 cuda threads
[2018-08-05 09:17:16] [S/A/T]: 0/1/1, diff: 0.004, 1366.96kH/s yes!
```

**Comment by papampi** [comment]
Tested both old miners with cuda 8 and new ones with cuda 9, working with no problems.

**Comment by LuKePicci** [comment]
I don't get the point of having miner's manifest files in this repo, they should be in the other one.

**Comment by papampi** [comment]
I didnt like it either, but creating 2 helpers folder was what I thought is not so good too.
So we move them to  $NVOC/miners/helpers/miner* ?

**Comment by LuKePicci** [comment]
I don't know at the moment what is best, but for sure the 2.1 branche does not need any more changes involving the pm model, which I would like to switch only in the future dev branch, otherwise I wouldn't take care of designing the basic support to those kind of miners to co-exist with old builtin ones. Focus thisPR on enablind dual cuda for existing builtin miners only, which is what we have now.

**Comment by papampi** [comment]
Then what about miner update script that now only depends on miners manifest?

**Comment by papampi** [comment]
Have you seen my last commit?
https://github.com/papampi/nvOC_miners/commit/0c377ebea39a52c611b688f947f5eb1cb54dee39

**Comment by LuKePicci** [comment]
In my intentions it should not depend on manifests for builtin miners, and the current branch for miner installer/compiler script should not have anything related to pluggable model inside, that's why I asked you to take only the reworked get-sources (and update-symlink) functions, which are good for supporting multi-source for builtin miners as well.

**Comment by LuKePicci** [comment]
Your last commit is almost exactly the final step of the pm revolution but I don't think we are ready for it, not yet.

**Comment by papampi** [comment]
Then whats your suggestion on implementing dual cuda into 2.1?

**Comment by LuKePicci** [comment]
My switchover roadmap plan is something like this:
- start creating manifests for current miners in the repo
- test running a miner as pm while it is still defined as builtin
- test its install and compile logic by plugging in a copy of that same miner
- switch its installation and compilation logic to pm model by removing the installer & compile section from the script and adding its manifest to the repo
- remove any reference for that miner as a builtin miner from the main nvOC sources

dual-cuda is conceptually a feature that only makes sense with the old builtin miners so it is a workaround that we need to support the current 2.1 branch, and I think what you were doing is pretty fine to achieve this result, the pluggable model is the future, and is not ready. You were just missing the multi-source code and I did it in such a way that it works either with future pm's or the current builtin ones, so take get-sources function from my branch, and use it where it is used already by adding the extra argument for commit hash and it is ok. Do it starting from https://github.com/papampi/nvOC_miners/pull/19/commits/7a213e0a269aefe9c386bc70cc0e3905efc5ec5d and should be fine

**Comment by LuKePicci** [comment]
Here is what should be done in details starting from that commit: https://github.com/papampi/nvOC_miners/pull/19#issuecomment-412304219

**Comment by papampi** [comment]
Fixed WTM_SWITCHER not getting data
I think its better if Instead of exit if couldn't get BTC price it try to read from last price from WTM_BTC_EXCHANGE_RATE if it exists. 
 
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/ac79801ac3bc491be05ec5eda0d1c1569bb06e40/WTM_SWITCHER#L87

**Review by LuKePicci — CHANGES_REQUESTED** [review]
That's fine, just retarget the miners submodule to main branch once it gets merged before merging this one.

**Comment by papampi** [comment]
All good?
Ready to merge?
Merge miners and then this one?

**Comment by papampi** [comment]
Miners merged ...

**Review by LuKePicci — APPROVED** [review]

**Pull request merged**
