### PR TITLE
2unix update miners on first boot

### PR DESCRIPTION
**Pull request by papampi**

### CODE REVIEW

**Comment by papampi** [comment]
We can also add version file inside miners folder to check it for miners update and 3main notify user if a miner update is available.

**Comment by LuKePicci** [comment]
You first have to pull main repo updates otherwise you wont get miners updates.
You have to do git pull  on nvpc parent repo such that the linked submodule version is updated. After that, if you do git submodule update that submodule gets actually updated (pulled). This will prevent someone to pull a miners tree which is not supported by its nvoc version.

**Comment by LuKePicci** [comment]
For example, suppose you have a pre-built image with the current, as of today,  v2.1 branch cloned into it. On first boot, according to what you have coded it will check that the miners submodule is at version 94b35c95ff48e5b983f0a9a7a8b1b88592fb36bd and in case it's not it will pull updates. But this would only occur if you make a pre-built image without having previously updated that submodule by hand. I don't think this is the behavior you intended to get with this PR, right?

**Comment by papampi** [comment]
I'm looking for the easiest way to download and update miners either on first boot or later 
What you suggest?

**Comment by LuKePicci** [comment]
We have to discern two different functionalities, for each one we have different alternative approaches:
- First boot update
  - Clone the complete nvoc repo w/ its submodule dependencies (ie miners) from scratch, choosing between:
    - Latest major release (master branch): the nvOC os image clones the latest nvOC release
    - Latest minor release (release branch): the nvOC X.0 os image clones the latest nvOC X.Y release
  - Update an already cloned nvOC repo pulling updates for scripts and their linked miners module version
    - Again, either to latest major release, or miner one
  - Do not update anything, rely only on startup update
- Startup update
  - I would not cover this one here, since it has different kind of concerns to reason about

**Comment by papampi** [comment]
Is it possible to git clone to home folder and what happens to other files and folders ?
And what about changed 1bash when pulling update?

**Comment by LuKePicci** [comment]
> Is it possible to git clone to home folder and what happens to other files and folders ?

git clone to another directory, /home/m1/nvOC-X where X is the major release should be fine.in case of automatic minor updates, otherwise just /home/m1/nvOC

> And what about changed 1bash when pulling update?

You have to put in the small fat partition a batch script which download there the latest 1bash template intead of hardwriting an old template. After burnging the image, from windowso whatever else, just run that downlaoder, then edit 1bash as we have always done. After cloning the repo 1bash will be replaced
with the user modified one found in the small partition. Since the 1bash downloader will get that one for the same nvOC version the git pull will do should be fine.

**Comment by LuKePicci** [comment]
You won't need anymore to publish new images for every new nvOC releases, users won't need to setup an old 1bash template found in the fat partition just for booting up the first time, then update files and then re-edit the new 1bash version.

Apart from the cloning, you would then have to run ./nvOC install-service && start-service from inside the clone directory. This will automatically point to the right nvOC location, without having hardcoded nvOC path anywhere in the prebuilt image.

**Comment by papampi** [comment]
Oh, forgot the nvOC service, we dont need this PR at all ...

**Pull request closed without merging**
