### PR TITLE
Next step of WTM switcher cleanup & rework

### PR DESCRIPTION
**Pull request by LuKePicci**
Still WIP, seeing towards switches history log. Improved code readability and heavily simplified switching mechanics.

### CODE REVIEW

**Comment by papampi** [comment]
Can you explain more and tell me why it not sorts correct?

New one:
m1@m1-desktop-100:~$ python2.7 WTM_SWITCHER_1
BTC PRICE: 11312.65 USD
ZEC 4.69 USD
ZCL 4.39 USD
ETH 4.23 USD
ETC 3.88 USD
New profits
ZCL: 104 %
ZEC: 111 %
ETH: 100 %
ETC: 92 %

Old one:
m1@m1-desktop-100:~$ python2.7 WTM_SWITCHER
BTC PRICE: 11312.65 USD
New revenues
ZEC 4.69 USD
ZCL 4.39 USD
ETH 4.23 USD
ETC 3.88 USD
New profits
ZEC: 111 %
ZCL: 104 %
ETH: 100 %
ETC: 92 %

**Comment by LuKePicci** [comment]
I think you did a wrong copy&paste since the two examples you posted are the same one.
BTW that output is not shown in the same order of which the choice is made. I can fix this, I left untouched but it seems a non-functional issue.
This also caused me some headache since it was confusing me at the beginning, if you like to see the data sorted as wtm returns, and as the choice is performed just add a final "print data"

**Comment by LuKePicci** [comment]
Now it should look ok, tell me if you see something strange I didn't catch.

**Comment by papampi** [comment]
Looks good, Will put it in test and check more.
Thanks.

**Review by papampi — APPROVED** [review]
No problems found running for a week.

**Pull request merged**
