### PR TITLE
removed zec address

### PR DESCRIPTION
**Pull request by hartmanm**

### CODE REVIEW

**Comment by papampi** [comment]
Thats there so if for any reason user forgot to edit 1bash or the edited 1bash not copied miner start and dont get to problems.

**Comment by LuKePicci** [comment]
@hartmanm I don't know who own that zcash address, have you any concern about that?

**Comment by papampi** [comment]
I think thats fullzero address

**Comment by sizzlephizzle** [comment]
You can use mine.......hahaha

**Pull request closed without merging**
